# Generated by Django 4.0.3 on 2022-04-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('quote', models.TextField()),
                ('quote_owner', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=100)),
                ('publisher_img', models.ImageField(upload_to='blogs/')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50)),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogs')),
            ],
        ),
    ]
