# Generated by Django 4.0.3 on 2022-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
