# Generated by Django 4.0.3 on 2022-04-07 14:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='shop/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('1', 'Deactive'), ('2', 'Active'), ('3', 'Deactive'), ('4', 'Active'), ('5', 'Deactive'), ('6', 'Active'), ('7', 'Deactive'), ('8', 'Active')], max_length=50)),
                ('brand', models.CharField(choices=[('1', 'Deactive'), ('2', 'Active'), ('3', 'Deactive'), ('4', 'Active'), ('5', 'Deactive'), ('6', 'Active'), ('7', 'Deactive'), ('8', 'Active')], max_length=50)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('XS', 'XS'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=11)),
            ],
        ),
    ]
