# Generated by Django 4.0.3 on 2022-04-08 12:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brands_categories_alter_shops_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='sale',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shops',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], max_length=19),
        ),
    ]
