# Generated by Django 4.0.3 on 2022-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shops_sale_alter_shops_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shops',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
