# Generated by Django 4.0.3 on 2022-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_brands_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
