# Generated by Django 4.0.3 on 2022-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shops_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='image2',
            field=models.ImageField(default=1, upload_to='shop/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='image3',
            field=models.ImageField(default=1, upload_to='shop/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='image4',
            field=models.ImageField(default=2, upload_to='shop/'),
            preserve_default=False,
        ),
    ]
