# Generated by Django 4.0.3 on 2022-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shops_image2_shops_image3_shops_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='additional_information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shops',
            name='brief_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shops',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
