# Generated by Django 4.0.3 on 2022-04-11 13:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shops_image2_alter_shops_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], max_length=19, null=True),
        ),
    ]
