# Generated by Django 4.0.3 on 2022-05-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_title1_az_about_title1_en_about_title2_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title3_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title3_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
