# Generated by Django 4.0.3 on 2022-05-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_title3_az_about_title3_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
